// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mredodiufvtomhpidojd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yZWRvZGl1ZnZ0b21ocGlkb2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjI0MzMsImV4cCI6MjA3MTQ5ODQzM30.OnJMhkoGvl3bfl_WjeW_FdvS8oFdUUCccyhNaSTMU5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});